### ISSUE TITLE
power supply don't have memberID on some servers

### ISSUE THREAD

**Issue by jenningsloy318** [stmcginnis/gofish#136]
Hi colleageus,

some user report a issue in my repo  https://github.com/jenningsloy318/redfish_exporter/issues/29, indicated that the server model HP Proliant G9 servers and  ProLiant DL380 Gen9 don't have `memberID`.

**Comment by stmcginnis** [comment]
Thanks @jenningsloy318. It does look like the root cause is that HP server does not return expected information. I will watch for any updates on that issue to see if there is something that can be done on the gofish side.

They may just need to upgrade their server firmware to get the latest iLO, assuming HPE has fixed compliance to the spec.

**Comment by stmcginnis** [comment]
I'm assuming HPE has since fixed this, based on the notes captured in the redfish_exporter issue.
