### ISSUE TITLE
Redfish version

### ISSUE THREAD

**Issue by pallasscat** [stmcginnis/gofish#197]
Good day,

Is there a specific version of Redfish spec this library is conforming to?

I noticed that some properties (e.g. `Processor/OperatingSpeedMhz` ) are missing or are using deprecated properties (e.g. `Storage/StorageControllers`); this is something I may be able to fix with my limited experience with Go.

**Comment by stmcginnis** [comment]
Thanks @pallasscat. This library tries to handle a range of spec versions, so there may be a mix of some older, deprecated properties along with newer ones.

There are also some objects that have not been fully implemented, just because they might not have been needed by anyone at the time. Those do need to be added at some point.

I am probably overdue for picking up the latest releases of the spec. There are scripts under the `tools/` directory for extracting the details and generating a lot of the code. That was mostly for the initial generation of a lot of the code. What I've done since then is use that to compare the generated code with what is already in the library to see where there are things missing or changed.

If you'd like to take a look at some of the newer spec changes, that would be great. Contributions definitely welcome. Otherwise I will get to it at some point. I just haven't had a lot of time to focus on this library lately.

Thanks!

**Comment by pallasscat** [comment]
Thanks for a quick reply, @stmcginnis, I'll try to go through some of the spec changes (the ones I need) as soon as I can.

I'll take a look at it, thank you.
