### ISSUE TITLE
Code & code style review

### ISSUE THREAD

**Issue by pallasscat** [stmcginnis/gofish#200]
Hi @stmcginnis
I've commited to my fork, [link](https://github.com/stmcginnis/gofish/commit/53a40125cd892e35bb15839a0c3154533a7eda3a); can you go over the changes and see if I missed / messed anything up before I create a pull request?

Can you also confirm that the increase of comment length to 120 chars is acceptable?

**Comment by stmcginnis** [comment]
Very nice!

Yeah, comment length is fine. I think I've gotten over wanting to keep things readable in a smaller terminal window. :D

A few minor things like `x86ProcessorArchitecture` should stay `X86ProcessorArchitecture`. `ODataEtag` should be a string.

But overall, things look great. Thanks for working on this!

**Comment by pallasscat** [comment]
Great, I'll leave it at 120 chars then :D

Oh, completely my fault, thank you for noticing that; I'll have another proof-read.

Thank you!

While you're here:
1. I renamed `EthernetInterface` to `ProcessorEthernetInterface` to avoid duplicates. Is it an OK idea to use parent object (`Processor` in this case) as a prefix in similar scenarios?

2. I'm adding ``OEM json.RawMessage `json:"Oem"` `` fields for "possible" future updates, is it OK?

**Comment by stmcginnis** [comment]
> I renamed EthernetInterface to ProcessorEthernetInterface to avoid duplicates. Is it an OK idea to use parent object (Processor in this case) as a prefix in similar scenarios?

Is there actually a difference? Or is it just a common `EthernetInterface` object that is used in multiple places? If it is distinct, then yeah, that sounds like a good approach to prefix it to make it unique.

> I'm adding OEM json.RawMessage `json:"Oem"` fields for "possible" future updates, is it OK?

I actually noticed that and had to check. We currently have an odd mix of OEM fields being `json.RawMessage`, `string`, or `interface{}`. We should start to standardize on that. I think for the few things that have had vendor specific OEM handling added they are using the `RawMessage` approach, so that makes sense to start to standardize on that.

**Comment by pallasscat** [comment]
There is, objects have completely different fields. 2022.2 schema is more complex than the one current code is based on, and there will be more "collisions", I'm afraid. Not sure if I like the 2022.2 that much now, but oh well D:

Had the same thought and `json.RawMessage` is what seemed best to me - easier to use when adding code to `oem/`.
