### ISSUE TITLE
Error getting Chassis collection for DPU BMCs

### ISSUE THREAD

**Issue by iamsli** [stmcginnis/gofish#322]
Getting the below error when trying to get the chassis collection by 
`serviceRoot.Chassis()` on DPU BMCs 

```
error getting list of chassis: failed to retrieve some items: [{"link":"/redfish/v1/Chassis/Card1","error":"json: cannot unmarshal object into Go struct field .Controls of type common.Links"},{"link":"/redfish/v1/Chassis/Bluefield_BMC","error":"json: cannot unmarshal object into Go struct field .Controls of type common.Links"}]chassisList: [0xc0001c5b08]
```

**Comment by stmcginnis** [comment]
Ah, I think I see what the issue is. I can have a fix up shortly.

I'll start working on that, but just to confirm, would you be able to run the following to get the output from this machine? I've never worked with a DPU machine, so it would be great to see what it returns.

```sh
curl https:/$ADDR/redfish/v1/Chassis/Bluefield_BMC \
    -X GET \
    -k -s \
    -H "Content-type: application/json" \
    -u "$USER:$PASS" | jq .
```

If you don't have `jq` available you can omit that and just get the raw JSON response.

If you are unable to use `curl`, no worries. If you do know a way to get the output from the system with the tools you have, great. If not, I'm 99% certain I know the problem
